In [1]:
import yfinance as yf
data = yf.Ticker('600887.SS').history(start='2021-08-01', end='2021-10-01')[['Open','High','Low','Close']]

In [3]:
data['L14'] = data.Low.rolling(window=14).min()
data['H14'] = data.High.rolling(window=14).max()
data['%K'] = (data.Close - data.L14)/(data.H14 - data.L14) * 100
data['%D'] = data['%K'].rolling(window=3).mean()
data['check_line'] = data['%D'].rolling(window=3).mean()

In [4]:
import pandas_ta as ta
data.ta.stoch(high='High', low='Low', close='Close', k=14, d=3, append=True)

            STOCHk_14_3_3  STOCHd_14_3_3
Date
2021-08-19            NaN            NaN
2021-08-20            NaN            NaN
2021-08-23      13.627898            NaN
2021-08-24      14.373897            NaN
2021-08-25      18.253953      15.418583
2021-08-26      17.107560      16.578470
2021-08-27      18.871234      18.077582
2021-08-30      15.313068      17.097287
2021-08-31      27.035199      20.406500
2021-09-01      52.320968      31.556412
2021-09-02      75.984973      51.780380
2021-09-03      87.371051      71.892331
2021-09-06      81.234287      81.530104
2021-09-07      77.925327      82.176888
2021-09-08      74.868788      78.009467
2021-09-09      71.128609      74.640908
2021-09-10      70.800530      72.265976
2021-09-13      68.307086      70.078742
2021-09-14      64.763799      67.957139
2021-09-15      54.330731      62.467205
2021-09-16      49.409473      56.168001
2021-09-17      44.547393      49.429199
2021-09-22      42.778149      45.578339
2021-09-23      40.315647      42.547063
2021-09-24      53.673040      45.588945
2021-09-27      64.475088      52.821258
2021-09-28      76.564284      64.904138
2021-09-29      76.144577      72.394650
2021-09-30      79.453415      77.387425

In [5]:
data1 = yf.Ticker('600887.SS').history(start='2021-08-01', end='2021-10-01')[['Open','High','Low','Close']]
from stockstats import StockDataFrame as SDF
data1 = SDF.retype(data1)

In [6]:
import pandas as pd
data2 = pd.concat([data, data1[['kdjk', 'kdjd','kdjj']]], join='inner',axis=1)

In [7]:
data2.to_excel("stochastic_oscillator_calculation.xlsx")